const fakeData = [
  {
    id: 1,
    name: "LED Tv",
    company: "Samsung",
    price: "45,890",
    isAvailable: true,
    size: "4.5inc",
    category: "TV",
  },
  {
    id: 2,
    name: "Moto g60",
    company: "Motorola",
    price: "3470.78",
    isAvailable: true,
    size: "4.5inc",
    category: "MOBILE",
  },
  {
    id: 3,
    name: "Digital Clock",
    company: "Samsung",
    price: "45,890",
    isAvailable: true,
    size: "4.5inc",
    category: "CLOCK",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
  {
    id: 4,
    name: "Poco F1",
    company: "POCO",
    price: "45,890",
    isAvailable: true,
    size: "6.5inc",
    category: "MOBILE",
  },
]
export default fakeData
